services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: postgres
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pguser", "-d", "postgres", "-h", "localhost", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5