name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: '20.x'
    - run: cp .env.example .env
    - run: cd backend && cp .env.example .env && npm ci
    - run: docker compose up -d
    - run: cd backend && npm run build --if-present
    - run: cd backend && npm test
      env:
        PG_PORT: ${{ job.services.postgres.ports[5432] }}
