name: Docker build and test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: '20.x'
    - run: cp .env.example .env
    - run: docker compose build
    - run: docker compose up db -d
    - run: cd backend && cp .env.example .env && npm ci && npx prisma migrate deploy
    - run: cd backend && npm test
      env:
        PG_PORT: ${{ job.services.postgres.ports[5432] }}
