name: Lint Code Base
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: '20.x'
    - run: cd backend && npm ci && npm run lint
    - run: cd frontend && npm ci && npm run lint
